[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
mumbai = "${MATIC_RPC_URL}"

